/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ImplementacionEmpleados;
import Controlador.Login;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank
 */
public class LoginLavanderia extends javax.swing.JFrame {

    /**
     * Creates new form LoginLavanderia
     */
    private int intentosRestantes = 3;
    private Login empleado = new ImplementacionEmpleados();

    public LoginLavanderia() {
        initComponents();
        this.setLocationRelativeTo(this);

        SetImageLabel(logo, "src/main/java/Recursos/logoP.png");
        // SetImageLabel(imagenReferencial, "src/main/java/Recursos/referenfiacl.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        txtSession = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPasss = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 370, 430));

        txtSession.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        txtSession.setForeground(new java.awt.Color(0, 0, 0));
        txtSession.setText("INICIAR SESSION");
        bg.add(txtSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setText("USUARIO");
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        txtPass.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setText("CONTRASEÑA");
        bg.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 290, -1));

        txtPasss.setBackground(new java.awt.Color(255, 255, 255));
        txtPasss.setText("jPasswordField1");
        txtPasss.setBorder(null);
        bg.add(txtPasss, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 30));

        btnEntrar.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnEntrarLayout = new javax.swing.GroupLayout(btnEntrar);
        btnEntrar.setLayout(btnEntrarLayout);
        btnEntrarLayout.setHorizontalGroup(
            btnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnEntrarLayout.setVerticalGroup(
            btnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, 40));

        jPanel1.setBackground(new java.awt.Color(0, 175, 193));

        inUsuario.setBackground(new java.awt.Color(255, 255, 255));
        inUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        inUsuario.setForeground(new java.awt.Color(204, 204, 204));
        inUsuario.setText("Ingresar su nombre de usuario");
        inUsuario.setBorder(null);
        inUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(inUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(inUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inUsuarioActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
        String dniEmpleado = inUsuario.getText();
        String password = new String(txtPasss.getPassword());

        ImplementacionEmpleados empleado = new ImplementacionEmpleados();
        

        empleado.verificarLogin(dniEmpleado, password);

        if (empleado.isLoginExitoso()) {
            ModuloPrincipal modulo = new ModuloPrincipal();
            modulo.setVisible(true);
            this.dispose();
        } else {
            intentosRestantes--;

            if (intentosRestantes > 0) {
                JOptionPane.showMessageDialog(null, "Credenciales inválidas. Intentos restantes: " + intentosRestantes);
            } else {
                JOptionPane.showMessageDialog(null, "Se agotaron los intentos. Cerrando la aplicación.");
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginLavanderia().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnEntrar;
    private javax.swing.JTextField inUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel txtPass;
    private javax.swing.JPasswordField txtPasss;
    private javax.swing.JLabel txtSession;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
